bitbake.conf: fix PACKAGES multiple define breakage
Various upstream packages manually define a "-src" package and bitbake
errors out if a package is defined twice in PACKAGES (example below).

Don't unconditionally add ${PN}-src to PACKAGES because it will break
other recipes which actually want to add a ${PN}-src themselves. Also
don't unconditionally add the src dest to FILES_${PN} because it can
cause the same kind of breakage.

ERROR: python-twisted-13.2.0-r0 do_package: QA Issue: python-twisted-src is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
ERROR: python-twisted-13.2.0-r0 do_package: Fatal QA errors found, failing task.
ERROR: python-twisted-13.2.0-r0 do_package: Function failed: do_package
ERROR: Logfile of failure stored in: /media/adi/ssd/nilrt-krogoth/build/tmp-glibc/work/core2-64-nilrt-linux/python-twisted/13.2.0-r0/temp/log.do_package.11455
ERROR: Task 13 (/media/adi/ssd/nilrt-krogoth/build/../sources/meta-openembedded/meta-python/recipes-devtools/python/python-twisted_13.2.0.bb, do_package) failed with exit code '1'

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>